spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vmed
    username: root
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.SQL: debug